events {}

http {
    # Группа серверов для приложения
    upstream backend_app {
        server app:8000; # Имя сервиса из docker-compose
    }

    # Группа серверов для мониторинга
    upstream prometheus_service {
        server prometheus:9090;
    }

    server {
        listen 80;
        server_name localhost;

        # Проксируем основной API или веб-интерфейс
        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Проксируем доступ к панели Prometheus
        location /metrics-ui/ {
            proxy_pass http://prometheus_service/;
            proxy_set_header Host $host;
        }
    }
}
